server:
  port: 9883

spring:
  dna:
    datasource:
# build
#      jdbc-url: jdbc:tibero:thin:@10.188.162.177:8629:atidb
#      driver-class-name: com.tmax.tibero.jdbc.TbDriver
#      username: lab
#      password: rda0476!@#

# log4jdbc
      jdbc-url: jdbc:log4jdbc:tibero:thin:@112.169.69.112:8629:tibero
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #username: digital
      #password: digital1234
      username: digital_dev
      password: tibero
      
# Ongdalsaem
  small:
    datasource:
      jdbc-url: jdbc:tibero:thin:@10.188.162.185:8629:RDADB1
      driver-class-name: com.tmax.tibero.jdbc.TbDriver
      username: RDAEKPDIC
      password: RDAEKPDIC135

#thymeleaf
  thymeleaf:
    encoding: utf-8
    cache: false
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 100MB    # max file size - default 1MB
      max-request-size: 100MB # max request size - default 10MB

#mybatis
mybatis:
    type-aliases-package: com.digitalLab.Entity
    mapper-locations: classpath:/mappers/*.xml

# prjList
prjDtlInfoVo:
  setSysId: dnacare
  setSysPwd: EE44124C542D2BEB
